{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import Yesod

data Links = Links
instance Yesod Links

mkYesod "Links" [parseRoutes|
/ HomeR GET
/page1 Page1R GET
/page2 Page2R GET
/json_example JsonExample GET
|]

{-
"@{Page1R}" --> "http://localhost:3000/page1"
This is done using "renderRoute" function generated by the Template Haskell above
In the last example, JSON is returned instead of HTML, using Aeson library
Multiline quasiquotes are recommended for Hamlet, one line per tag
-}
getHomeR = defaultLayout [whamlet|
<a href=@{Page1R}>Go to page 1!
<br>
<a href=@{JsonExample}>Or get some JSON
|]

getPage1R = defaultLayout [whamlet|<a href=@{Page2R}>Go to page 2!|]
getPage2R = defaultLayout [whamlet|<a href=@{HomeR}>Go home!|]
getJsonExample = return $ object ["msg" .= ("Hello World" :: Value)]

main = warp 3000 Links